name: ask_a_dev_mobile
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Curly.png
    - assets/images/placeholder.png
  fonts:
    - family: Vera
      fonts:
        - asset: assets/fonts/Vera.ttf
        - asset: assets/fonts/Vera-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vera-Italic.ttf
          style: italic
    - family: VeraMono
      fonts:
        - asset: assets/fonts/VeraMono.ttf
          weight: 700
